### ISSUE TITLE
Beatslash makes Qtractor crashing

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qtractor#107]
Hi Rui, I've been trying to open the [beatslash-lv2 plugins](https://github.com/blablack/beatslash-lv2) in Qtractor 0.8.5 today and it makes Qtractor to crash (segfault) after loading the beatslash GUI.
Guestimate is that BeatSlash are CV compatibles but Qtractor doesn't handle that.

Would that then be possible to avoid such plugins (CV controled) to load up then makes Qtractor to crash? It would be much more user-friendly than the actual loading up + crash.

**Comment by rncbc** [comment]
yeah you're right, `lv2:cvport`s are not supported by any version of qtractor, and probably never will
those plugins are more suitable to hosts like `ingen` than anything else afaik.
so sorry.

**Comment by trebmuh** [comment]
nice 👍

**Comment by rncbc** [comment]
i now reckon that [beatlasher-lv2](https://github.com/blablack/beatslash-lv2) is using old [lvtk](https://github.com/lvtk/lvtk) which is the real culprit for the reported LV2 GUI crashes

lvtk is/was based on gtkmm and that's a big hindrance for a Qt host like Qtractor.

the case has nothing to do with `lv2:cvport`s but rather due to a pretty old GUI toolkit fundamental incompatibility.

so sorry that this won't get fixed anytime soon
byee

**Comment by trebmuh** [comment]
@blablack : anything you can do from your side maybe?

**Comment by blablack** [comment]
This plugin is using the latest officially released lvtk (1.2.0).

I had previously released them for lvtk 2.0 but many distros and software hadn't upgraded yet and it was causing many issues. 

That's gonna be a problem until lvtk 2.0 is officially released.
