### ISSUE TITLE
Synth settings not properly retained sometimes

### ISSUE THREAD

**Issue by gandalf3** [rncbc/qtractor#177]
I think I've somehow ended up with a qtractor session corrupted in such a way that some plugin parameters are not properly saved/restored (unless this is the effect of a feature I'm not aware of). 

There's a midi track with "MT Chip Waltz" chosen in a Helm instance. Restarting qtractor causes the settings of this Helm instance to be scrambled, though the chosen patch is remembered. Helm sounds different until the patch is re-selected. A similar thing happens to the ZynAddSubFX in the second track in the same session, except the selected patch is completely forgotten.

For some reason this only seems to happen on these two tracks; new tracks with ZynAddSubFX or Helm function as expected.

I've attempted to reproduce this behavior in a new qtractor session and could not. Even so, the behavior once introduced is reproducible every time, so I've [attached a simplified session](https://github.com/rncbc/qtractor/files/2544556/settings_not_retained.tar.gz) derived from the project I encountered this in (please don't mind any bits of irrelevant cruft left over).

**Comment by rncbc** [comment]
have you tried whether selecting the very same patches (or presets, banks or programs) onto a new session tracks the problem gets reproduced ?

**Comment by rncbc** [comment]
I now believe this is a deep fundamental bug in Helm (and ZynAddSubFX) LV2 versions and their use of the lv2_programs custom extension (the one that let's you select a patch via MIDI channel Bank_Select and Program_Change methods. 

Somehow, you once messed with it at at least on a Track's properties dialog ie. you touched at least once on the Instrument, Bank or Program fields. So that you mapped an instrument patch (bank, program) to a MIDI channel in the working session. Now this setting (bank_select, program_change) also gets saved on the MIDI clip files that you edit or create under the session. On session load and playback, these MIDI bank_select+program_change messages get obviously directed to the plugins chain on MIDI tracks, getting handled by the lv2_programs extension if implemented. As a matter of fact, the kxstudio versions of the Helm (and ZynAddSubFX) instrument plugins have this lv2_programs extension implemented, but I believe they are not being handled right with respect with LV2 plugin state and parameters.

I bet the VST versions of the plugins work right wrt. selecting programs.

I'll keep investigating though...

**Comment by rncbc** [comment]
confirmed. the VST versions work as expected wrt. MIDI bank_select/program_change functionality.

The LV2 implementation seems to make mess with global state, preset and parameters when switching programs.

As a rule, for the time being: when using Qtractor and any the LV2 plugin versions of Helm, ZynAddSubFX (and possibly others from the kxstudio builds), please DON'T EVEN TOUCH ONCE any the "Bank" and/or "Program" fields, on any MIDI track's properties, away from "(None)".

hth.
Cheers

**Comment by gandalf3** [comment]
Amazing, thanks! I did indeed mess with those settings.

I tried loading my project in https://github.com/rncbc/qtractor/commit/a76e6914, setting and un-setting instrument/bank/program, saving, and re-opening, but experienced the same behavior as before. Is there something I'm missing?

Also, should I report this upstream to Helm and Zyn?

**Comment by rncbc** [comment]
As said, the issue is probably related to the LV2 implementations, as the VST seems to work correctly.

**Comment by gandalf3** [comment]
I can confirm the VST versions seem to work for the most part, though for me helm is much quieter until the patch is re-selected.

I had thought that resetting the instrument/bank/program on the track in https://github.com/rncbc/qtractor/commit/a76e6914 would remove the program change messages in the appropriate clips?

**Comment by rncbc** [comment]
> I had thought that resetting the instrument/bank/program on the track in a76e691 would remove the program change messages in the appropriate clips?

there's no program_change in the clips; previously it was saving bank=0 and prog=0 in the session file, even though you reset both to "none"; when loading the session again the first bank/program is then always selected, overriding the saved plugin state and parameters.

**Comment by gandalf3** [comment]
I see. I manually removed the bank and program tags from the session and now it seems fine, however, I would've thought that setting them to "none" would do that for me (with https://github.com/rncbc/qtractor/commit/a76e69140fb8e5f26fa8a31a85d6c556ea265231 of course).
