### ISSUE TITLE
qtractor 0.9.3 crash with calf-fluidsynth

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qtractor#181]
calf-fluidsynth (git master 85c4e4e) is opening fine with qtractor 0.9.2, but is crashing qtractor 0.9.3

**Comment by trebmuh** [comment]
ping @boomshop

**Comment by rncbc** [comment]
if you can build qtractor from source, try ./configure --enable-lv2-ui-gtk2 (needs all libgtk2-dev and resp. deps.);

the issue is possible rooted on your libsuil-gtk2_in_qt5 installation and not quite on qtractor per se; the ./configure --enable-lv2-ui-gtk2 builds a native wrapper in qtractor, overriding the one from libsuil; this build option has been now disabled on default on v0.9.3.

hth.

**Comment by trebmuh** [comment]
@rncbc Thanks Rui, it worked perfectly.
Closing then.
