### ISSUE TITLE
Qtractor doesn't unload VST3 modules after you close it.

### ISSUE THREAD

**Issue by oldcastlehq** [rncbc/qtractor#326]
Hi,

I'm using yabridge-host.exe to run Windows plugins, and I noticed that the process keep running even when I close all the plugins. Then I found this info at https://github.com/robbert-vdh/yabridge 

> Some hosts, particularly Ardour, REAPER, Qtractor, will by default not unload VST3 modules after you close the last plugin. This means that the associated yabridge-host.exe process will keep running until you close the project. For REAPER there's an option called Allow complete unload of VST plug-ins in the VST tab of the settings dialog to disable this behaviour.

Can Qtractor implements something similar to the Reaper solution?

**Comment by rncbc** [comment]
i'm afraid it can't be done because at least qtractor keeps the plugin loaded all the time until the session is closed for say, undo/redo reasons and  that happens for any plugin type, not just VST3.

so that even though you remove the plugin it will still be loaded in the background, just not activated.

**Comment by oldcastlehq** [comment]
Ok. Understood.
