### ISSUE TITLE
MIDI CC 10 is sent whenever CC 7 is sent

### ISSUE THREAD

**Issue by suedwestlicht** [rncbc/qtractor#425]
While playing with automation in MIDI tracks I noticed: Whenever MIDI CC 7 is sent (volume), by automation of the fader or by painting CC 7 events in a clip, there is also permanently CC 10 sent, even when the playhead stops.

This makes problems when trying to automate a fader or a plugin's parm because it always sets CC 10.

Workaround:
Choose another MIDI CC or block CC 10 with a MIDI filtering plugin.

**Comment by rncbc** [comment]
ack.

MIDI tracks volume (CC#7) and panning (CC#10) are hard-wired to the mixer sliders ever since the beginning of times (year 2007 in qtractor universe:))

also, the state of those sliders are sent out whenever playback starts, subject to View > Options... > MIDI > Playback > Reset all controllers on playback start, though.

so, iow. both CC7 and CC10 might always apply for all _declared_ MIDI track/channels, no matter automation is in place or not.

hth.

**Comment by suedwestlicht** [comment]
OK, then it works as designed.
