### ISSUE TITLE
Automation issues

### ISSUE THREAD

**Issue by thebutant** [rncbc/qtractor#64]
As a very passionate and grateful Qtractor user, there are a couple of issues I tend to stumble upon when working in Qtractor. Two of these occur when automating.

1/ Say I'm using the same plugin for multiple tracks (for example a Calf Filter for a bass track and another Calf Filter for an organ track), and I'm automating these to sound as good as possible. Sometimes (not always, but also not seldom) after reopening the project, one of the automations have copied the other. So one Calf Filter automation is gone, or rather is exactly like the other one. If I then automate it once again to make it sound good, it will most likely (actually I think "always" is more correct) go back to be a copy of the other automation after reopening the project.

For a while I suspected this would only happen if I dragged the plugin from the one track to the other, simply copying it, but it happens also when adding a new instance.

This can be a bit frustrating and eat up a lot of time. Especially when it happens to multiple plugins in the same project - when you have to re-adjust a filter here, a reverb there and then check that the other plugins aren't out of place.

2/ A newer issue (at least for me) is that automation values have suddenly adjusted themselves when reopening a project. If I set a gain value to 1,4, I reopen and find it to be something like 1,382. They seem to always adjust just a tad down, so it rarely does any harm. Still, there was a reason I put it to 1,4 in the first place.
I have the high resolution plugin automation enabled, I don't know if that has anything to do with this.

These are just a couple of small things, but they still make me spend quite a lot of extra time simply adjusting automations I've already adjusted.

But to clear all doubts: Qtractor is still my favourite. <3

**Comment by rncbc** [comment]
re. 1/ - that is of course strange and indices for a serious bug in there. I'll try t o investigate and get back here as ssoon as possible.

re. 2/ yes, that's all indeed somewhat expected as all automation data is stored in standard MIDI 14-bit the so called high-resolution (!), so that the source parameter scalar value might get  quantized over the available 14-bit range--it's a fact this quantization error is more noticeable as large is the plugin's parameter value scale range.

cheers && thanks

**Comment by rncbc** [comment]
re. 1/ - the issue have been spotted when one has two (or more) tracks with **exact** same name and at least one same plugin type in common: the generated automation/curve data filenames may get confused and drastically overwritten, being the last in track and plugin listing order the one that prevails.

this is now hopefully fixed on git_head (v0.8.1.25git+)

please test && tell
cheers

**Comment by thebutant** [comment]
Ah, that makes sense!
Then I'll make sure to rename my tracks in order to avoid this.

Or rather: Thank you for fixing it!

**Comment by rncbc** [comment]
re. 1/ you may notice that, once the fix is in effect, all track names now become unique, or enforced otherwise, by adding an incremental number suffix, if any.

if you're still using any previous version--older than v0.8.2--you're hereafter fully recommended to rename all track-name dupes. on your watch.

hth.
cheers

**Comment by thebutant** [comment]
That's a safe and clever way to fix it.
Thanks!
